import { Inter } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="p-10">
      <body className={inter.className}>
        <nav>
          <ul className="flex gap-5">
            <Link href={"/"}>Home</Link>
            <Link prefetch={false} href={"/about"}>About</Link>
            <Link href={"/blog"}>Blog</Link>
          </ul>
        </nav>
        <hr className="mt-3" />
        {children}
      </body>
    </html>
  );
}
